project:
  type: website
  output-dir: docs
website:
  title: "R project"
  
  navbar:
    background: primary
    search: false
    tools:
      - icon: github
        menu:
          - text: Github link
            href: https://github.com/Lambda-ck/R-project.git
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Statistique descriptive"
        href: statistique.qmd
      - text: "Analyse de données"
        href: Analyse des données.qmd
        
  sidebar:
      style: "docked"
      background: light
      contents:
        - text: "Membres du groupe :"
        - "- Emma Andre"
        - "- Jade Ducos"
        - "- Julien Lascaux"
        - "- Lucas Coussy"
  
        
format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

